// Code generated by xgo (XGo); DO NOT EDIT.

package main

import "github.com/go-wyvern/gplot"

const _ = true

type vector struct {
	gplot.Figure
}
//line vector.plot:1
func (this *vector) MainEntry() {
//line vector.plot:1:1
	a := gplot.Linspace(0, 2*gplot.Pi, 20)
//line vector.plot:2:1
	this.Plot__2(a, (gplot.Vector).Gop_Mul(a, a))
}
func (this *vector) Main() {
	gplot.Gopt_Figure_Main(this)
}
func main() {
	new(vector).Main()
}
