// Code generated by xgo (XGo); DO NOT EDIT.

package main

import "github.com/go-wyvern/gplot"

const _ = true

type index struct {
	gplot.Figure
}
//line index.plot:1
func (this *index) MainEntry() {
//line index.plot:1:1
	a := []float64{1, 3, 5, 7.0}
//line index.plot:2:1
	b := []float64{1, 3, 5.0, 7}
//line index.plot:3:1
	this.NominalX("s1", "s2", "s3", "s4")
//line index.plot:4:1
	this.Bar(a, b)
}
func (this *index) Main() {
	gplot.Gopt_Figure_Main(this)
}
func main() {
	new(index).Main()
}
