// Code generated by xgo (XGo); DO NOT EDIT.

package main

import "github.com/go-wyvern/gplot"

const _ = true

type Axis1 struct {
	gplot.Axis
	*index
}
type Axis2 struct {
	gplot.Axis
	*index
}
type index struct {
	gplot.Figure
	Axis1 Axis1
	Axis2 Axis2
}
//line index.plot:6
func (this *index) MainEntry() {
//line index.plot:6:1
	gplot.Gopt_Figure_Run(this, 1, 2)
}
func (this *index) Main() {
	gplot.Gopt_Figure_Main(this)
}
//line Axis1.axis:1
func (this *Axis1) Main() {
//line Axis1.axis:1:1
	a := gplot.Linspace(0, 2*gplot.Pi, 20)
//line Axis1.axis:2:1
	this.Xlabel("x")
//line Axis1.axis:3:1
	this.Ylabel("x*x")
//line Axis1.axis:4:1
	this.Title("fig1")
//line Axis1.axis:5:1
	this.Plot__2(a, (gplot.Vector).Gop_Mul(a, a))
}
//line Axis2.axis:1
func (this *Axis2) Main() {
//line Axis2.axis:1:1
	a := gplot.Linspace(0, 2*gplot.Pi, 20)
//line Axis2.axis:2:1
	this.Xlabel("x")
//line Axis2.axis:3:1
	this.Ylabel("sin(x)")
//line Axis2.axis:4:1
	this.Title("fig2")
//line Axis2.axis:5:1
	this.Plot__2(a, gplot.Sin__1(a))
}
func main() {
	new(index).Main()
}
