// Code generated by xgo (XGo); DO NOT EDIT.

package main

import "github.com/go-wyvern/gplot"

const _ = true

type index struct {
	gplot.Figure
}
//line index.plot:1
func (this *index) MainEntry() {
//line index.plot:1:1
	x := gplot.Linspace(0, 2*gplot.Pi, 20)
//line index.plot:2:1
	this.Plot__2(x, gplot.Sin__1(x), x, gplot.Cos__1(x))
}
func (this *index) Main() {
	gplot.Gopt_Figure_Main(this)
}
func main() {
	new(index).Main()
}
